name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.3
    - uses: cachix/install-nix-action@v11
    - uses: cachix/cachix-action@v6
      with:
        name: mjlbach
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build build.nix
    - run: nix-shell --run "echo OK"
